### PR TITLE
Refactor segmentation pipeline

### PR DESCRIPTION
**Pull request by wolny**
This branch introduces `PipelineExecutor` abstraction which offloads the work to a separate thread pool, thus unblocking the UI.
I've removed the hacks around `sys.stdout` which allowed for logging into the GUI frame and introduced a separate `gui_logger` that can be used for this purpose (I followed: https://github.com/beenje/tkinter-logging-text-widget/blob/master/main.py).

- [x] refactor `GenericProcessing` and pipeline steps hierarchy
- [x] allow multi-threaded execution of the pipeline to free up the GUI thread

### CODE REVIEW

**Comment by wolny** [comment]
I'd postpone unit tests and remaining code cleanup to be done in a separate PR.

**Comment by lorenzocerrone** [comment]
my comments before merging:

- logging is a bit verbose `2020-02-07 15:26:48,218 [ThreadPoolExecutor-0_0] INFO PlantSeg etc `
 wouldn't make sense to prune it a bit? like just date and time `02-07 15:26: etc`, in the end this logger is not for debugging but only for the user.
- errors some are shown in the gui some in a pop-up (is it wanted?) if yes is fine form me. 
- directory structure must be agreed, now is changed. 
- Preprocessing / Postprocessing run time shows is always zero. Even thought I/O takes quite a few seconds. Should we remove it?

**Comment by wolny** [comment]
1. :heavy_check_mark: left only the date and time
2. :heavy_check_mark: if the event logged with `gui_logger` is `ERROR` or `CRITICAL` it will show in the popup
3. WIP
4. :heavy_check_mark: I removed the the logging time for the pre/post-processing

**Comment by wolny** [comment]
:shipit:

**Pull request merged**
