### PR TITLE
Remove pytorch-3dunet dependency

### PR DESCRIPTION
**Pull request by wolny**
- [x] remove pytorch3dunet dependency
- [x] simplify prediction code
- [x] optimize prediction
- [x] bring back DataParallel
- [x] test on 8gpu node  
- [x] find optimal batch size
- [x] remove striding options from the gui
- [x] test new and legacy gui/headless
- [x] automatically set patch size in the widget based on the model name

### CODE REVIEW

**Comment by wolny** [comment]
fixes: https://github.com/hci-unihd/plant-seg/issues/130

**Comment by wolny** [comment]
fixes: https://github.com/hci-unihd/plant-seg/issues/128

**Comment by wolny** [comment]
this is ready from my side :rocket:

**Comment by wolny** [comment]
I'm really starting to like the `magicgui`, I wanted the patch size to be changed automatically based on the model selection and I can do it with one callback:

```
@widget_unet_predictions.model_name.changed.connect
def _on_model_name_changed(model_name: str):
    train_config = get_train_config(model_name, config_only=True)
    patch_size = train_config['loaders']['train']['slice_builder']['patch_shape']
    widget_unet_predictions.patch_size.value = patch_size
```

**Comment by lorenzocerrone** [comment]
> I'm really starting to like the `magicgui`: I wanted the patch size to be changed automatically based on the model selection and I can do it with one callback heart_eyes :
> 
> ```
> @widget_unet_predictions.model_name.changed.connect
> def _on_model_name_changed(model_name: str):
>     train_config = get_train_config(model_name)
>     patch_size = train_config['loaders']['train']['slice_builder']['patch_shape']
>     widget_unet_predictions.patch_size.value = patch_size
> ```



> I'm really starting to like the `magicgui`: I wanted the patch size to be changed automatically based on the model selection and I can do it with one callback heart_eyes :
> 
> ```
> @widget_unet_predictions.model_name.changed.connect
> def _on_model_name_changed(model_name: str):
>     train_config = get_train_config(model_name)
>     patch_size = train_config['loaders']['train']['slice_builder']['patch_shape']
>     widget_unet_predictions.patch_size.value = patch_size
> ```

Yes! I totally I agree, I didn't use any of them so far! But I want to add a lot more call backs, in particular for the image rescaling, the cropping, io, and the proofreading!

**Comment by lorenzocerrone** [comment]
https://github.com/hci-unihd/plant-seg/blob/00ff55acc6fee5195dfcb38cc5560a2e54915438/plantseg/predictions/functional/utils.py#L72

Cool! :)

**Comment by lorenzocerrone** [comment]
Looks great! 
The only part where I disagree with the changes in how we move the data on the GPUs and the logic around that. I don't like the `.cuda()` for several reasons:
- It does not allow users to select the GPU from the Napari UI. 
- User wanting to run two models on the same image in parallel (I do this often to see which model is better)
- User has two GPUs (one for running display and one for computing)  and does not want the code to run on the display GPU. 
- User has a Mac (the new one with metal support) and can't use the cuda but can use the `mps` backend. 
- I think this will break the headless workflow (but I need to check that).

We should always specify the devices and use the `.to(devices)` syntax.
And we should change the UI to be able to select multiple devices.

**Comment by wolny** [comment]
> Looks great! The only part where I disagree with the changes in how we move the data on the GPUs and the logic around that. I don't like the `.cuda()` for several reasons, it does not allow:
> 
> * Users to select the GPU from the Napari UI.
> * User wanting to run two models on the same image in parallel (I do this often to see which model is better)
> * User has two GPUs (one for running display and one for computing)  and does not want the code to run on the display GPU.
> * User has a Mac (the new one with metal support) and can't use the cuda but can use the `mps` backend.
> * (and) I think this will break the headless workflow (but I need to check that).
> 
> We should always specify the devices and use the `.to(devices)` syntax. And we should change the UI to be able to select multiple devices.

fair enough! I used this semantic, so that `DataParallel` works correctly. It's definitely possible to have `input.to(device)` working correctly (the forward pass it's the model which is replicated on each device and it should not matter where is the input), but I need to check what happens when you do `model.to(device)`. Anyway we can make that work with having an additional option `all gpus` in the UI, which should be the default for headless.

**Comment by lorenzocerrone** [comment]
Sounds good, let's merge it! 

I think we can still use cuda parallel in a idiomatic form, we just need to pass the device ids in the dataparallel (so option 2).  

If you want I can tackle this :) So you can focus on spoco!

**Review by lorenzocerrone — APPROVED** [review]

**Pull request merged**
