### PR TITLE
Add documentation folder and Actions for https://hci-unihd.github.io/plant-seg/

### PR DESCRIPTION
**Pull request by qin-yu**
I created a Jupyter Book (Sphinx) based doc structure. Jupyter Book allow us to include Jupyter Notebook style code block and its actual ouptut in the doc, but before you need/do this, the book is just Sphinx. Existing Wiki is ported to it with minor modifications in links, and this commit is co-authored. The GitHub action in this branch is only for this branch, for testing. The website is at https://hci-unihd.github.io/plant-seg/

When the PR is merged, we need to change the branch to master (or a dedicated branch called say `publish` to reduce the frequency of Doc rebuilding) in the Action file `.github/workflows/build-deploy-book.yml`.

Note that in Wiki we can use GitHub hosted images with `blob` URL, but here we can only use `raw` URL, see https://gist.github.com/qin-yu/cb9039b0eda130c4ea14ae330a74e8b1

If the doc grows we can automate the ToC generation in the future.

### CODE REVIEW

**Comment by lorenzocerrone** [comment]
Fantastic job! Thanks Qin! I looks good to me

**Review by lorenzocerrone — APPROVED** [review]
looks good!

**Comment by wolny** [comment]
Awesome! Thx @qin-yu

**Comment by qin-yu** [comment]
Repo home's description now use Pages as the website.

**Pull request merged**
